# Generated by Django 5.1.1 on 2024-10-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='carpeta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='jugadores.carpeta'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='seleccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='trayectoria',
            field=models.TextField(max_length=200),
        ),
    ]
