# Generated by Django 5.1.1 on 2024-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_carpeta_carpeta_padre_alter_jugador_seleccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='img3',
        ),
        migrations.AddField(
            model_name='jugador',
            name='perfil_pdf',
            field=models.FileField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
